name: Build iOS App

on:
  push:
    branches: [master, main, develop]
    paths:
      - "ios/**"
      - ".github/workflows/build-ios.yml"
  pull_request:
    branches: [master, main]
    paths:
      - "ios/**"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install dependencies
        run: |
          # Install XcodeGen
          brew install xcodegen

          # Generate Xcode project from project.yml
          cd ios
          xcodegen generate

          # Install CocoaPods dependencies (if needed in future)
          # pod install --repo-update || true

      - name: Build for Simulator
        run: |
          cd ios
          xcodebuild build \
            -scheme SpeechMastery \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build \
            -arch arm64 \
            -verbose

      - name: Build for Device (Attempt to skip signing)
        run: |
          cd ios
          xcodebuild build \
            -scheme SpeechMastery \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath build \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \          # <-- REMOVED SPACES/QUOTES
            CODE_SIGNING_REQUIRED=NO \       # <-- Added
            CODE_SIGNING_ALLOWED=NO \        # <-- Added
            2>&1 | head -100 || true
        continue-on-error: true

      - name: Run Unit Tests
        run: |
          cd ios # <-- Change directory to 'ios' (where the .xcodeproj is)
          xcodebuild test \
            -scheme SpeechMastery \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -verbose \
            2>&1 | tail -50 || true
        continue-on-error: true

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: ios/build/
          retention-days: 7

      - name: Build Status
        if: always()
        run: echo "Build completed. Check artifacts above."
